### ISSUE TITLE
ghc-exactprint-0.1.0.0 doesn't compile with GHC 7.8.4

### ISSUE THREAD

**Issue by peti** [alanz/ghc-exactprint#1]
I get the following error:

    Building ghc-exactprint-0.1.0.0...
    Preprocessing library ghc-exactprint-0.1.0.0...
    [1 of 3] Compiling Language.Haskell.GHC.ExactPrint.Types ( src/Language/Haskell/GHC/ExactPrint/Types.hs, dist/build/Language/Haskell/GHC/ExactPrint/Types.o )

    src/Language/Haskell/GHC/ExactPrint/Types.hs:111:20:
        Not in scope: type constructor or class ‘GHC.AnnKeywordId’

    src/Language/Haskell/GHC/ExactPrint/Types.hs:135:20:
        Not in scope: type constructor or class ‘GHC.DataId’
        Perhaps you meant ‘GHC.DataCon’ (imported from GHC)

A complete build log is at http://hydra.cryp.to/build/522473/nixlog/2/raw.

**Comment by mpickering** [comment]
Hi Peter,

Thanks for the report. The package only compiles with GHC 7.10 RC2.

**Comment by peti** [comment]
It might be a good idea to have the Cabal file reflect that?

**Comment by alanz** [comment]
Agree, will do so for next version, due out soon.

I only put it on hackage to try and get HaRe running against travis, but bumped into a cabal issue there, so will wait for RC2, due soon

**Comment by alanz** [comment]
Should the description in the cabal file reflect this, or can I enforce it in the build-tools or similar?

**Comment by peti** [comment]
I believe the best way to declare the dependency on GHC 7.10.x is to add the snippet

    if impl (ghc < 7.10)
        buildable: false

to the library stanza.

**Comment by alanz** [comment]
If I set it to

```
library
  exposed-modules:     Language.Haskell.GHC.ExactPrint
                     , Language.Haskell.GHC.ExactPrint.Types
                     , Language.Haskell.GHC.ExactPrint.Utils
  -- other-modules:
  -- other-extensions:
  build-depends:       base >=4.7 && <4.9
                     , containers
                     , ghc
                     , ghc-paths
                     , syb
  hs-source-dirs:      src
  default-language:    Haskell2010
  if impl (ghc < 7.10)
      buildable: False
```

I can still `cabal configure` with GHC 7.8.4. What am I missing?

**Comment by peti** [comment]
Try `cabal build`. :smile:

**Comment by alanz** [comment]
blush.

Will push a new version soon.
