### ISSUE TITLE
Doesn't build with GHC-8.6.1-alpha

### ISSUE THREAD

**Issue by ChShersh** [alanz/ghc-exactprint#65]
When I try to build `ghc-exactprint` with `ghc >= 8.6` in my dependencies, I see the following error:

```haskell
src/Language/Haskell/GHC/ExactPrint/Types.hs:370:7: error:
    Not in scope: data constructor ‘GHC.VectD’
    Neither ‘DynFlags’, ‘GHC’ nor ‘Outputable’ exports ‘VectD’.
    |
370 |       GHC.VectD d       -> f (GHC.L l d)
    |       ^^^^^^^^^
```

I could try to fix it by myself but I don't even know where to find Haddock for latest GHC...

**Comment by alanz** [comment]
Did you try [this](https://github.com/alanz/ghc-exactprint/tree/ghc-8.6) branch?

**Comment by ChShersh** [comment]
@alanz Oh, I wasn't aware of this branch! Very cool, I will try it.

Do you by any chance know how can I depend on this branch in my project where I use `cabal`?

**Comment by alanz** [comment]
I do it via git submodules, see e.g. https://github.com/alanz/HaRe/blob/ghc-8.6/cabal.project

And I use `cabal new-build`

**Comment by ChShersh** [comment]
@alanz Thanks a lot! I've managed to build my project with `ghc-exactprint` and everything works as expected for now. Though, I don't use submodules. I've just manually cloned your repo. Also, I've commented dependency from `hashable-1.2.7.0` in your `cabal.project` since this version is already on Hackage.
